### ISSUE TITLE
List items from a given project view

### ISSUE THREAD

**Issue by tomMoulard** [github/gh-projects#46]
Let's say that my project have multiple views, I would like to list item that are on this view. This could be done by allowing to specify a filter, or a view number to get the corresponding filter.

For example, I created a project https://github.com/users/tomMoulard/projects/2, and a corresponding repo to open issues in.
On the first view, I filtered to only see issues with the `view` custom field set to 1. On the second, I did the same using `view: 2`.

I get:

```bash
$ gh projects item-list 2 --user tomMoulard
Type   Title    Number  Repository       ID
ISSUE  Issue 1  1       tomMoulard/temp  PVTI_lAHOAJtkds4AMytTzgFOyEU
ISSUE  Issue 2  2       tomMoulard/temp  PVTI_lAHOAJtkds4AMytTzgFOyGY
```

I would like to do either of the following:

```bash
$ gh projects item-list 2 --user tomMoulard --view 1
Type   Title    Number  Repository       ID
ISSUE  Issue 1  1       tomMoulard/temp  PVTI_lAHOAJtkds4AMytTzgFOyEU

$ # or
$ gh projects item-list 2 --user tomMoulard --filter "view: 2"
Type   Title    Number  Repository       ID
ISSUE  Issue 2  2       tomMoulard/temp  PVTI_lAHOAJtkds4AMytTzgFOyGY
```

Another nice to have would be to also have custom fields displayed as such:

```bash
$ gh projects item-list 2 --user tomMoulard
Type   Title    Number  Repository       ID                            Status  view
ISSUE  Issue 1  1       tomMoulard/temp  PVTI_lAHOAJtkds4AMytTzgFOyEU  Todo    1
ISSUE  Issue 2  2       tomMoulard/temp  PVTI_lAHOAJtkds4AMytTzgFOyGY  <nil>   2
```

WDYT ?

**Comment by mntlty** [comment]
@tomMoulard thank you for the suggestions! 

I like adding `--view 1` to filter.

For custom fields, I think adding them will potentially make the length of the display really long, and potentially not fitting in their terminal window. This is ok on the web, but less ideal in a terminal. What do you think?

**Comment by mntlty** [comment]
@tomMoulard I spent some time playing around with the api for view https://docs.github.com/en/graphql/reference/objects#projectv2view

It doesn't have a field for `items` to filter for only items that are visible in that view, which is what I understood the request to be about (please correct me if I'm wrong!).

It does support `groupByField` and `sortByField` which contains the items that are visible in that view, but becomes difficult to replicate in a terminal, as the view may be a Board, Table, or a Roadmap. General support for Views in the terminal is a direction I'm avoiding for this extension.

**Comment by tomMoulard** [comment]
I'm sorry, I am not well acquainted with GitHub's API.

> It does support `groupByField` and `sortByField` which contains the items that are visible in that view, but becomes difficult to replicate in a terminal, as the view may be a Board, Table, or a Roadmap. General support for Views in the terminal is a direction I'm avoiding for this extension.

Very well, This issue is not about replicating the view output in the terminal. It is more on seeing/using the view content.

Therefore, a filter option would be more feasible, and the `--view` argument would start by betting the view filter, and the applying it to fetch items.

As for custom fields, I was planning on using it with other tools, like AWK, to filter the output and getting each field data. Therefore, the length of the line is not that important to me.
Having said that, It could be interesting to change completely the output of the command to have it ingested by other programs. For example, we could have it export the items in a JSON format, and being able to export more data this way.
As this is completely another discussion, I can open another issue to discuss this further if you want.

**Comment by mntlty** [comment]
another user also opened an issue https://github.com/github/gh-projects/issues/47 requesting a `filter` option, which makes a lot of sense! It's not currently supported by the api, but it will be easy to update the extension once it is available.

regarding the machine output in a format like JSON, I agree that it would be very helpful and something I would like to spend some time thinking about how to do.
