### ISSUE TITLE
[feature request] item-list with search filter

### ISSUE THREAD

**Issue by maxbeizer** [github/gh-projects#47]
When I want to list items in a project I would love to be able to use the same syntax as the filter in the web view. Something like:

```
gh projects item-list 123123 --org github --filter "no:status assignee:@me"
```

Honestly I don't recall if we have built the filter string into the API yet but that seems like a real nice improvement if we can do it

**Comment by mntlty** [comment]
@maxbeizer agreed! I don't see a `filter` argument on the `items` field in https://docs.github.com/en/graphql/reference/objects#projectv2 which is needed to offer that functionality 😞

**Comment by mntlty** [comment]
@maxbeizer agreed! This would be very useful. Unfortunately the API doesn't support this today,so I'm going to close this issue, please reopen when that changes!

It is possible to fetch all project items and display the result in JSON or CSV, which I'm currently working on, and would allow for client side filtering with JQ or something similar.

**Comment by mntlty** [comment]
@maxbeizer JSON support is now available in https://github.com/github/gh-projects/releases/tag/v1.2.0
