### ISSUE TITLE
`gh projects item-add` url is case sensitive

### ISSUE THREAD

**Issue by rajbos** [github/gh-projects#49]
# Description
The url parameter is case sensitive and does not report that back to the user (just shows the options)

Working example:
`gh projects item-add 13 --org XpiritBV --url https://github.com/XpiritBV/project-demo/issues/241`

Non working example (notice the url)
`gh projects item-add 13 --org XpiritBV --url https://github.com/xpiritbv/project-demo/issues/241`

# Expectation:
Either support it (the web UI does as well), or give an proper error code back to the user.

# Note:
The `org` name is __not__ case sensitive

**Comment by mntlty** [comment]
fixed in https://github.com/github/gh-projects/releases/tag/v1.1.0

**Comment by rajbos** [comment]
I've upgraded, new error: `v1.1.0`:

![image](https://user-images.githubusercontent.com/6085745/223956705-10813f86-6db2-4c1f-ab2b-e0dde4a6feb3.png)

**Comment by mntlty** [comment]
I don't have access to your repo, it seems like it's not able to find the resource based on the URL. Are you able to try

```
gh api graphql -F url='https://github.com/github/gh-projects/pull/55' -F query='
query GetResource($url: URI!) {
	resource(url: $url) {
		__typename
		... on Issue {
			id
		}
		... on PullRequest {
			id
		}
	}
}
'
```

with your URL and share the output? I've confirmed the above works for me, returning
```
{
  "data": {
    "resource": {
      "__typename": "PullRequest",
      "id": "PR_kwDOIsbF2c5LmozW"
    }
  }
}
```
and `null` for the resource when it isn't found

**Comment by mntlty** [comment]
hmm, that means I'm going to have to revert this change, and do better error handling. thanks for the report!
