### ISSUE TITLE
Running the extension without repo context gives strange results

### ISSUE THREAD

**Issue by rajbos** [github/gh-projects#51]
On windows: `unknown resource type` for this command:
`gh projects item-add 13 --org xpiritbv --url https://github.com/xpiritbv/project-demo/issues/238`

Getting the project list works:
`gh projects list --org xpiritbv --limit 10`

**Comment by mntlty** [comment]
@rajbos I'm not very familiar with the differences with windows, I wonder if wrapping the url in quotes will help?

**Comment by mntlty** [comment]
duplicate of https://github.com/github/gh-projects/issues/49
