### ISSUE TITLE
Limit option on `item-list` does not seem to be working

### ISSUE THREAD

**Issue by victorp13** [github/gh-projects#67]
`gh projects item-list` has the option `--limit` that should default to 100. Instead, not using this option returns all items, and using this option also returns all items.

**Comment by mntlty** [comment]
@victorp13 you're right! I introduced a bug when I introduced pagination. 

Looking at the command, I'm inclined to remove the limit and always fetch all of the items from item-list. Users can filter if they want less, but I have mixed feelings about an artificial limit, or a magic number like `-1` to bypass it.

What do you think?
