### ISSUE TITLE
How create the project under a repository? 

### ISSUE THREAD

**Issue by NMSAzulX** [github/gh-projects#76]
1. How create the project under a repository? 
2. When I run `gh projects edit $NEW_PROJECT_NUM --org ${{github.repository_owner}} --visibility PUBLIC` . 
There is an error:`Viewer not authorized to change project visibility, Locations: [{Line:1 Column:56}]`

**Comment by mntlty** [comment]
Hi @NMSAzulX !

1. A ProjectV2 is owned by an org or a user, not a repository, as was the case for Projects Classic. There is currently no command or option in the extension to link a Project with a repo, but you can do so with `gh api graphql` and this mutation https://docs.github.com/en/graphql/reference/mutations#linkprojectv2torepository

2. It seems like you don't have admin permission on the project you are trying to make public

**Comment by NMSAzulX** [comment]
@mntlty Thank you for replying so quickly. I will carefully examine the second problem. In addition, whether has plan to add a query API for example: 
```
 # query projects by name
 query{
      organization(login:$user){
             id
             projectsV2(first:$num, query:"$name") {
                nodes{
                number
                    id
                    ...
                }
              }
 }
```

**Comment by mntlty** [comment]
@NMSAzulX  with the command `gh projects list --format=json` and then filter for values with for projects using `jq` or any other JSON utility

**Comment by NMSAzulX** [comment]
@mntlty Hello. Could you take a moment to instruct me to configure admin permissions? I have clicked all the buttons and opened all permissions, including Github APP Settings. It still has no effect.

![image](https://user-images.githubusercontent.com/16236903/225223685-2deb25c2-fd38-4c6e-aa8d-ae5d2aaeedbc.png)
![image](https://user-images.githubusercontent.com/16236903/225223723-9109c228-cd80-4bd4-95e1-a7d1adab4c81.png)
![image](https://user-images.githubusercontent.com/16236903/225224346-49fabc2d-baf1-416d-a3fa-c7023113c6b4.png)

![image](https://user-images.githubusercontent.com/16236903/225223562-bdf800f3-6d0d-4501-b948-b199322c2e1a.png)

![image](https://user-images.githubusercontent.com/16236903/225223839-367e5a40-e116-4bc7-b19a-b9ad90f34e23.png)

![image](https://user-images.githubusercontent.com/16236903/225223381-597f59e2-569b-48b8-9cff-6e9e6e56fa27.png)

**Comment by mntlty** [comment]
I've confirmed that the `gh projects edit --visibility PUBLIC` command is working at expected with a project that I have created in an org I am an admin of. Unfortunately I am not in a position to provide general support on GitHub Projects.

Hopefully this helps with the UI https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-visibility-of-your-projects#changing-project-visibility
if you cannot perform these action in the UI, then you won't be able to perform them via the APIs either.

**Comment by NMSAzulX** [comment]
@mntlty 
I can change the visibility manually. But API doesn't work. Maybe Github doesn't recognize me as the administrator of this organization. :) There are two owners of this organization, and I am one of them.
I'm not sure if this problem has anything to do with Github APP's callback.
The following is the code related to my certification.

![image](https://user-images.githubusercontent.com/16236903/225230710-e234777e-50aa-443a-87b9-bbcc200e13fd.png)
Thank you for your help. I will close this issue and continue to find the answer.
