### ISSUE TITLE
content doesn't contain custom fields

### ISSUE THREAD

**Issue by eddumelendez** [github/gh-projects#80]
Previous to version 2, by executing `gh projects item-list $PROJECT_ID --org $ORG --format json | jq` I was able to get custom fields in the content, which I found useful to perform some queries against those. Please restore this.

**Comment by eddumelendez** [comment]
Sorry, I was making a mistake and didn't see the value.

**Comment by mntlty** [comment]
@eddumelendez can I close this issue?

**Comment by eddumelendez** [comment]
I though it was closed. Yes!
