### ISSUE TITLE
Add ability to update item field values

### ISSUE THREAD

**Issue by mntlty** [github/gh-projects#84]
I have implemented the basics for this in https://github.com/github/gh-projects/commit/ec75c3f94b0212064cc765c59462ae85b655b26c the challenges I see stem from these being two different API mutations, with different required inputs, outputs, and possible failure modes. 
I'd like to keep the API intuitive and accessible, and I feel like pushing these two together goes against that idea. At the same time, having two similar but subtly different commands, say `draft-item-edit` and `item-edit` (or `item-edit` and `field-values-edit`) feels cumbersome and requires the user be very aware of the type of item they are operating on.

I'm not sure what the best path forward is, and welcome feedback from the community.

**Comment by samcoe** [comment]
@mntlty My thoughts are that you are correct that it feels odd to require the user to be aware of the type of item they are operating on. I think the approach of a single `item-edit` command that properly handles draft items, erroring out when necessary, is going to be the best user experience despite it requiring more logic (basically two separate code paths) inside the command.

**Comment by mntlty** [comment]
@samcoe thank you as always for the feedback ❤️ 

Good documentation being a hard problem, is there a way highlight the different usages for users that you are aware of that feels effective other than adding a lot of words to [draft](https://github.com/github/gh-projects/blob/ec75c3f94b0212064cc765c59462ae85b655b26c/cmd/item-edit/item_edit.go#L61) ?

As a concrete example:
```
# edit the title of a Draft Issue
gh projects item-edit --id DI_XXX --title

# edit the value of the number field on github org project number 5 to have value 4
gh projects 5 item-edit --id PVTI_XXX --field-id PVTF_XXX --number 4 --org github
```

All of the fields are required and mutually exclusive (with the exception of the `--id` field which is required by both) depending on whether the user is intending to update the properties of a draft issue or the field values of an item which can be a draft issue, issue, or pull request.

**Comment by samcoe** [comment]
Unfortunately having lengthy docs that are explicit is the only effective solution to the problem that I can think of. I don't see that as a problem though, more of a side effect of having a complex command stemming from having a complex product. There will likely be some learning curve for our users but that is okay, as long as we give them the resources to effectively learn. 

One thing to look into is perhaps `cobra` has a way of segregating flags? I haven't looked into it but it would be nice if the help docs separated the flags into subsections based on what type of item they could be used for.
